services:
  bot:
    build: .
    restart: unless-stopped
    environment:
      - DISCORD_APIKEY=${DISCORD_APIKEY}
      - DISCORD_CLIENTID=${DISCORD_CLIENTID}
      - OPENROUTER_APIKEY=${OPENROUTER_APIKEY}
      - OPENAI_APIKEY=${OPENAI_APIKEY}
      - OPENAI_ORG=${OPENAI_ORG}
      - OPENAI_PROJECT=${OPENAI_PROJECT}
      - FIRECRAWL_APIKEY=${FIRECRAWL_APIKEY}
    volumes:
      - db-data:/app/data

volumes:
  db-data:
